// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAyKunJTW7M8HYYbw4_mr4cRrEQAKYNbU',
    appId: '1:196776411273:web:bc8ddcd94a6660ec400658',
    messagingSenderId: '196776411273',
    projectId: 'authtutorial-deec1',
    authDomain: 'authtutorial-deec1.firebaseapp.com',
    storageBucket: 'authtutorial-deec1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMC6FfFg4eDN8AoiRjTmyj9i_AfQ5BiuM',
    appId: '1:196776411273:android:96b1053ccee2af2c400658',
    messagingSenderId: '196776411273',
    projectId: 'authtutorial-deec1',
    storageBucket: 'authtutorial-deec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ClSITMF1zLNkiJ2pc7zJhlO2LLYxwsE',
    appId: '1:196776411273:ios:6bd31866d3faece7400658',
    messagingSenderId: '196776411273',
    projectId: 'authtutorial-deec1',
    storageBucket: 'authtutorial-deec1.appspot.com',
    iosClientId: '196776411273-smubqm57vdsbit6bbbqiurg80hmuap1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ClSITMF1zLNkiJ2pc7zJhlO2LLYxwsE',
    appId: '1:196776411273:ios:6bd31866d3faece7400658',
    messagingSenderId: '196776411273',
    projectId: 'authtutorial-deec1',
    storageBucket: 'authtutorial-deec1.appspot.com',
    iosClientId: '196776411273-smubqm57vdsbit6bbbqiurg80hmuap1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
